sudo: required
services:
  - docker

before_install:
  - docker build -t alivekiwi/sg-dnk-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true alivekiwi/sg-dnk-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'sg-dnk-frontend'
  env: 'sg-dnk-frontend-env'
  bucket_name: 'elasticbeanstalk-us-east-1-354528709752'
  bucket_path: 'sg-dnk-frontend'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
